services:
  app-js:
    image: volodymyrbjj/app-js
    restart: always
    tty: true
    build:
      context: .
    container_name: app-js
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    networks:
      - app-network


networks:
  app-network:
    external: true